// Auto-generated by .hooks/generate.py — DO NOT EDIT
// OpenCode Plugin: Sylph Harness Hooks
// Platform: OpenCode
// Generated: 2026-05-03

import { execSync } from "child_process";
import { existsSync } from "fs";
import { join, resolve } from "path";

const PROJECT_ROOT = resolve(import.meta.dirname || process.cwd(), "../..");
const DEBUG = process.env.SYLPH_HOOKS_DEBUG === "1";

interface HookEntry {
  name: string;
  script: string;
  timeout: number;
  blocking: boolean;
}

function runHook(entry: HookEntry, input: any): { continue: boolean; error?: string } | null {
  const absScript = join(PROJECT_ROOT, entry.script);
  if (!existsSync(absScript)) {
    if (DEBUG) console.error(`[sylph-hooks] Script not found: ${absScript}`);
    return null;
  }
  try {
    const result = execSync(`bash "${absScript}"`, {
      input: JSON.stringify(input),
      timeout: entry.timeout,
      encoding: "utf-8",
      stdio: ["pipe", "pipe", "pipe"],
    });
    return JSON.parse(result.trim());
  } catch (e: any) {
    // exit code 2 = hard block (our hook protocol)
    if (e.status === 2) {
      return { continue: false, error: e.stderr?.toString() || "Blocked by hook" };
    }
    return null;
  }
}

function processHooks(entries: HookEntry[], input: any): boolean {
  for (const entry of entries) {
    const result = runHook(entry, input);
    if (result && result.continue === false) {
      if (DEBUG) console.error(`[sylph-hooks] Blocked by ${entry.name}: ${result.error}`);
      return false;
    }
  }
  return true;
}

export default async ({ $ }: any) => {
  // ── Before hooks — can block execution ──
  const beforeHooks: HookEntry[] = [
  { name: "permission_gate", script: ".claude/hooks/permission-gate.sh", timeout: 5000, blocking: true },
  { name: "privacy_gate", script: ".claude/hooks/privacy-gate.sh", timeout: 3000, blocking: true },
  ];

  // ── After hooks — observe only ──
  const afterHooks: HookEntry[] = [
  { name: "completion_gate", script: ".claude/hooks/completion-gate.sh", timeout: 10000, blocking: true },
  { name: "bash_audit", script: ".claude/hooks/posttool-bash-audit.sh", timeout: 5000, blocking: false },
  ];

  // ── Session hooks — fire on session start ──
  const sessionHooks: HookEntry[] = [
  // No session hooks configured
  ];

  // ── Prompt hooks — fire on user message ──
  const promptHooks: HookEntry[] = [
  { name: "user_correction_detector", script: ".claude/hooks/pretool-user-correction.sh", timeout: 3000, blocking: false },
  ];

  // ── Idle hooks — fire on session idle ──
  const idleHooks: HookEntry[] = [
  // No idle hooks configured
  ];

  return {
    "tool.execute.before": async (input: any, _output: any) => {
      const allowed = processHooks(beforeHooks, input);
      if (!allowed) {
        throw new Error("Blocked by Sylph harness hook");
      }
    },

    "tool.execute.after": async (input: any, _output: any) => {
      processHooks(afterHooks, input);
    },

    "session.created": async (input: any, _output: any) => {
      processHooks(sessionHooks, input);
    },

    "chat.message": async (input: any, _output: any) => {
      const allowed = processHooks(promptHooks, input);
      if (!allowed) {
        throw new Error("Blocked by Sylph prompt hook");
      }
    },

    "session.idle": async (input: any, _output: any) => {
      processHooks(idleHooks, input);
    },
  };
};
