#!/usr/bin/env node
// EXTRACT-FONTS — 站点 webfont 真值提取（机制 §十五）
// 用法: node scripts/ui-restore/extract-fonts.mjs <url> --task home_page [--out public/fonts]
// 原理: 1) 页面内 document.fonts 拿到已加载 family/weight/status 真值
//       2) 抓取全部样式表（外链 + 内联）正则解析 @font-face { family, weight, src url }
//       3) 下载 woff2/woff/ttf → public/fonts/
//       4) 生成 src/styles/fonts.scss（@font-face 指向 /fonts/ 本地文件）
// 幂等: 已存在的字体文件跳过下载；fonts.scss 全量重写（内容同源，无副作用）
// 为什么: 跨域 CSS 的 cssRules 不可读，但 href 可拉取；resource timing 可能被隐藏，
//         故样式表正则解析是真值来源。webfont 缺失会导致全站文本宽度/行高漂移（pill 78 vs 74 类残差）
import { chromium } from 'playwright';
import { writeFileSync, mkdirSync, existsSync } from 'fs';
import { join, basename } from 'path';
import { loadTask, REPO_ROOT } from './task-config.mjs';

const [url, ...flags] = process.argv.slice(2);
const opt = (n, d) => { const i = flags.indexOf(n); return i > -1 ? flags[i + 1] : d; };
if (!url) { console.error('usage: extract-fonts.mjs <url> --task X [--out public/fonts]'); process.exit(1); }
const TASK = opt('--task', 'home_page');
const cfg = loadTask(TASK);
const FONT_DIR = join(REPO_ROOT, opt('--out', 'public/fonts'));
const SCSS_OUT = join(REPO_ROOT, 'src', 'styles', 'fonts.scss');
mkdirSync(FONT_DIR, { recursive: true });

// ── 1) 页面真值：已加载字体 + 样式表清单 ──
const b = await chromium.launch({ headless: true });
const page = await b.newPage({ viewport: { width: cfg.vw, height: cfg.vh } });
await page.goto(url, { timeout: 90000, waitUntil: 'domcontentloaded' });
await page.waitForTimeout(6000); // 等 webfont 加载完毕
await page.evaluate(() => document.fonts.ready);
const pageTruth = await page.evaluate(() => ({
  loaded: [...document.fonts].map(f => ({ family: f.family, weight: f.weight, style: f.style, status: f.status })),
  sheets: [...document.styleSheets].map(s => s.href).filter(Boolean),
  inline: [...document.querySelectorAll('style')].map(s => s.textContent || '').filter(t => t.includes('@font-face')),
}));
await b.close();
console.log('页面已加载字体:', JSON.stringify(pageTruth.loaded.filter(f => f.status === 'loaded')));
console.log(`样式表 ${pageTruth.sheets.length} 个外链, ${pageTruth.inline.length} 个内联含 @font-face`);

// ── 2) 解析全部 CSS 的 @font-face ──
const FACE_RE = /@font-face\s*{([^}]*)}/g;
const prop = (block, name) => (block.match(new RegExp(`${name}:\\s*([^;]+);`)) || [])[1]?.trim();
const faces = [];
const cssTexts = pageTruth.inline.map(t => ({ text: t, base: url })); // 内联样式相对页面解析
for (const href of pageTruth.sheets) {
  try {
    const res = await fetch(href);
    if (res.ok) cssTexts.push({ text: await res.text(), base: href }); // 外链 CSS 相对自身路径解析
  } catch (e) { console.log(`  CSS 拉取失败 ${href.slice(0, 60)}: ${e.message.slice(0, 40)}`); }
}
for (const { text: css, base } of cssTexts) {
  for (const m of css.matchAll(FACE_RE)) {
    const block = m[1];
    const family = prop(block, 'font-family')?.replace(/['"]/g, '');
    const src = block.match(/url\(([^)]+)\)/);
    if (!family || !src) continue;
    const srcUrl = src[1].replace(/['"]/g, '');
    const weight = prop(block, 'font-weight') || '400';
    const style = prop(block, 'font-style') || 'normal';
    const fmt = (block.match(/format\(['"]?([\w-]+)['"]?\)/) || [])[1] || '';
    faces.push({ family, weight, style, srcUrl, fmt, base });
  }
}
console.log(`解析到 @font-face ${faces.length} 条`);

// ── 3) 下载字体文件（幂等）──
const scss = [`// GENERATED by extract-fonts.mjs — 站点 webfont 真值（源: ${url}）`, '// 重新提取: node scripts/ui-restore/extract-fonts.mjs <url> --task ' + TASK, ''];
for (const f of faces) {
  let absUrl;
  try { absUrl = new URL(f.srcUrl, f.base).href; } catch { console.log(`  非法 src 跳过: ${f.srcUrl.slice(0, 50)}`); continue; }
  const ext = (absUrl.match(/\.(woff2?|ttf|otf)(\?|$)/) || [])[1] || 'woff2';
  const file = `${f.family.replace(/\s+/g, '')}-${f.weight}${f.style === 'italic' ? 'i' : ''}.${ext}`;
  const dest = join(FONT_DIR, file);
  if (!existsSync(dest)) {
    try {
      const res = await fetch(absUrl);
      if (!res.ok) throw new Error(`HTTP ${res.status}`);
      writeFileSync(dest, Buffer.from(await res.arrayBuffer()));
      console.log(`  ↓ ${file} (${f.family} ${f.weight})`);
    } catch (e) { console.log(`  下载失败 ${file}: ${e.message.slice(0, 50)}`); continue; }
  } else console.log(`  = ${file} 已存在跳过`);
  const format = ext === 'woff2' ? 'woff2' : ext === 'woff' ? 'woff' : ext === 'ttf' ? 'truetype' : 'opentype';
  scss.push('@font-face {');
  scss.push(`  font-family: '${f.family}';`);
  scss.push(`  font-style: ${f.style};`);
  scss.push(`  font-weight: ${f.weight};`);
  scss.push(`  font-display: swap;`);
  scss.push(`  src: url('/fonts/${file}') format('${format}');`);
  scss.push('}', '');
}
writeFileSync(SCSS_OUT, scss.join('\n'));
console.log(`→ ${SCSS_OUT}（在 global.scss 顶部 @use/import 生效）`);
