#!/usr/bin/env python3
"""
clarify_engine.py — Goal 前置澄清引擎

管道:
1. 读取用户原始描述
2. 逐条追问 4 个模块：目标(Goal) / 验收条件(AC) / 边界(Scope) / 依赖(Deps)
3. 输出标准 spec.md

spec.md 格式:
    # Spec: {title}
    ## 目标
    - 一句话目标
    ## 验收条件
    - AC1: <description>  [command:|file:|assertion:]
    - AC2: ...
    ## 边界
    - In Scope: [项1, 项2, ...]
    - Out of Scope: [项3, ...]
    - 冻结规则: ...
    ## 依赖
    - 前置条件: ...
    - 外部依赖: ...

参数:
    - --title: 任务标题 (可选, 默认从描述推断)
    - --interactive: 交互式追问模式 (默认)
    - --batch: 批量模式 (从 stdin 读取预定义 Q&A)
    - --output: spec.md 输出路径

用法:
    python3 clarify_engine.py --title "重构 verify_gate" --output spec.md --batch
    python3 clarify_engine.py --title "文档更新"  # 交互式
"""

import json
import os
import re
import sys
from datetime import datetime, timezone
from pathlib import Path


# ─── 默认提示语池 ───
PROMPT_TEMPLATES = {
    "goal": {
        "question": "🎯 目标：这个任务要达成什么？一句话讲清楚。",
        "hint": "例：「给 verify_gate.py 加 AC 逐条验证」「重构 archive_engine 打包逻辑」",
    },
    "ac": {
        "question": "✅ 验收条件（每一条都是一个可验证的断言）：",
        "hint": "每条以 command:/file:/assertion: 开头\nexample:\n  - command: `python3 verify_gate.py --step S1` 应输出 VERIFIED\n  - file: spec.md 应包含所有 AC\n  - assertion: 状态机自动推进到 ARCHIVED",
    },
    "scope_in": {
        "question": "📦 范围 — IN：这个任务必须覆盖哪些文件/模块？",
        "hint": "例：.omc/scripts/carros_base.py, .omc/scripts/goal_state_machine.py",
    },
    "scope_out": {
        "question": "⛔ 范围 — OUT：明确不做什么？",
        "hint": "例：不改 CI/CD 配置，不改数据库 schema",
    },
    "deps": {
        "question": "🔗 依赖和前置条件：",
        "hint": "依赖哪些现有功能？需要什么前置条件？",
    },
    "done": {
        "question": "🎬 可以了。确认以上内容？(y/n) ",
        "hint": "y -> 输出 spec.md | n -> 重新编辑",
    },
}


def _parse_ac_line(line):
    """解析 AC 行 — 返回 (id, type, description)

    AC 行可带或不带 AC 编号前缀。
    格式:
        "AC1 [command:] python3 verify_gate.py 输出 VERIFIED"
        "[command:] python3 verify_gate.py 输出 VERIFIED"
        "AC1: 描述"
        "assertion: 描述"
    """
    stripped = line.strip().lstrip("-").strip()
    if not stripped:
        return None, "assertion:", ""

    # 匹配: AC1 [command:] desc 或 AC1: desc
    m = re.match(r"(AC\d+)\s*(?:\[(command:|file:|assertion:)\]\s*)?:\s*(.+)", stripped)
    if m:
        return m.group(1), m.group(2) or "assertion:", m.group(3)

    # 匹配: AC1 [command:] desc (无冒号)
    m = re.match(r"(AC\d+)\s*\[(command:|file:|assertion:)\]\s*(.+)", stripped)
    if m:
        return m.group(1), m.group(2), m.group(3)

    # 匹配: AC1: desc
    m = re.match(r"(AC\d+):\s*(.+)", stripped)
    if m:
        return m.group(1), "assertion:", m.group(2)

    # 匹配: [command:] desc 或 command: desc
    m = re.match(r"\[?(command:|file:|assertion:)\]?\s*(.+)", stripped)
    if m:
        return None, m.group(1), m.group(2)

    # 纯描述 — 默认 assertion
    return None, "assertion:", stripped


def _validate_ac_line(line):
    """验证 AC 行的格式 — 返回 (ok, error_message)"""
    _id, _type, desc = _parse_ac_line(line)
    if _id is None and not desc.strip():
        return False, "AC 行不能为空"
    if not desc.strip():
        return False, f"AC 描述不能为空"
    if _type not in ("command:", "file:", "assertion:"):
        return False, f"AC 类型必须是 command:/file:/assertion:，当前: {_type}"
    return True, ""


def build_spec(title, goal, acs, scope_in, scope_out, deps_section):
    """构建 spec.md 内容"""
    lines = [
        f"# Spec: {title}",
        "",
        f"**Created:** {datetime.now(timezone.utc).strftime('%Y%m%d %H:%M UTC')}",
        f"**Schema:** goal-spec.v1",
        "",
        "---",
        "",
        "## 目标",
        "",
    ]
    lines.append(f"{goal}")
    lines.append("")

    # 验收条件
    lines.append("## 验收条件（每条必须可验证）")
    lines.append("")
    ac_index = 1
    for ac_line in acs:
        _id, _type, desc = _parse_ac_line(ac_line)
        prefix = f"AC{ac_index} [{_type}]" if _type else f"AC{ac_index}"
        lines.append(f"  - {prefix} {desc}")
        ac_index += 1
    lines.append("")

    # 边界
    lines.append("## 边界")
    lines.append("")
    lines.append("### In Scope")
    for item in scope_in:
        lines.append(f"  - {item}")
    lines.append("")
    lines.append("### Out of Scope")
    for item in scope_out:
        lines.append(f"  - {item}")
    lines.append("")
    lines.append("**冻结规则：不改 scope 声明、不改 AC 数量、不改 AC 类型。**")
    lines.append("")

    # 依赖
    lines.append("## 依赖和前置条件")
    lines.append("")
    lines.append(deps_section if deps_section else "无")
    lines.append("")
    lines.append("---")
    lines.append("_Generated by clarify_engine.py_")
    lines.append("")

    return "\n".join(lines)


def _interactive_clarify(title):
    """交互式澄清 — 逐条追问 4 个模块"""
    print(f"\n{'='*60}")
    print(f"📋 Goal 前置澄清: {title}")
    print(f"{'='*60}\n")

    goal = _prompt_with_hint("goal")
    if not goal:
        goal = "未定义 (请编辑 spec.md 补充)"
        print(" ⚠ 目标为空，将继续")

    print(f"\n--- 验收条件 ---")
    print(f"输入 AC（每行一条），输入空行结束：")
    acs = []
    while True:
        line = input("  AC> ").strip()
        if not line:
            if not acs:
                print(" ⚠ 至少需要一个 AC")
                continue
            break
        ok, err = _validate_ac_line(line)
        if not ok:
            print(f" ⚠ {err}，请重新输入")
            continue
        acs.append(line)
    if not acs:
        acs.append("AC1 [assertion:] 任务达到预期状态 (由用户后续补充)")
        print(" ⚠ 使用默认 AC")

    scope_in = _collect_scope_items("IN")
    scope_out = _collect_scope_items("OUT")
    deps = _prompt_with_hint("deps")

    # 确认
    print(f"\n{'='*60}")
    print("📝 确认内容：")
    print(f"  目标: {goal}")
    print(f"  ACs: {len(acs)} 条")
    print(f"  In Scope: {scope_in}")
    print(f"  Out of Scope: {scope_out}")
    print(f"  依赖: {deps or '无'}")

    confirm = input("\n确认以上内容？(Y/n): ").strip().lower()
    if confirm in ("n", "no"):
        print("\n重新开始...\n")
        return _interactive_clarify(title)

    return goal, acs, scope_in, scope_out, deps


def _prompt_with_hint(key):
    """打印提示并读取输入"""
    prompt = PROMPT_TEMPLATES.get(key, {})
    print(f"\n{prompt.get('question', '')}")
    print(f"  ({prompt.get('hint', '')})")
    value = input("> ").strip()
    return value


def _collect_scope_items(direction):
    """收集 In/Out of Scope 项"""
    print(f"\n--- Scope {direction} ---")
    items = []
    while True:
        item = input(f"  {direction}> ").strip()
        if not item:
            if not items:
                print(f" ⚠ 至少需要一个 {direction} 项")
                continue
            break
        items.append(item)
    return items


def _batch_clarify(title):
    """批处理模式 — 从 stdin 读取结构化 Q&A"""
    import sys as _sys
    raw = _sys.stdin.read().strip()
    if not raw:
        print("⚠ batch mode: empty stdin, fallback to interactive")
        return _interactive_clarify(title)

    try:
        data = json.loads(raw)
        goal = data.get("goal", data.get("target", ""))
        raw_acs = data.get("acs", data.get("acceptance_criteria", []))
        acs = []
        for ac in raw_acs:
            if isinstance(ac, str):
                acs.append(ac)
            elif isinstance(ac, dict):
                # { "type": "command:", "desc": "..." }
                prefix = ac.get("type", "assertion:")
                desc = ac.get("desc", ac.get("description", ""))
                acs.append(f"{prefix}{desc}" if not desc.startswith("AC") else desc)
        scope_in = data.get("scope_in", data.get("in_scope", []))
        scope_out = data.get("scope_out", data.get("out_scope", []))
        deps = data.get("deps", data.get("dependencies", ""))
        return goal, acs, scope_in, scope_out, deps
    except json.JSONDecodeError:
        # 当纯文本传进来时
        print(f"⚠ batch: parse as plain text: {raw[:60]}...")
        return raw, ["AC1 [assertion:] 见目标描述"], [], [], ""


def main(argv=None):
    import argparse

    parser = argparse.ArgumentParser(description="Goal 前置澄清引擎")
    parser.add_argument("--title", default=None, help="任务标题")
    parser.add_argument("--output", default=None, help="spec.md 输出路径")
    parser.add_argument("--interactive", action="store_true", default=True,
                       help="交互式模式 (默认)")
    parser.add_argument("--batch", action="store_true",
                       help="批处理模式 (从 stdin 读 JSON)")
    args = parser.parse_args(argv)

    title = args.title or "unnamed-task"
    output_path = Path(args.output) if args.output else Path(".omc") / "spec.md"

    if args.batch:
        goal, acs, scope_in, scope_out, deps = _batch_clarify(title)
    else:
        goal, acs, scope_in, scope_out, deps = _interactive_clarify(title)

    spec_content = build_spec(title, goal, acs, scope_in, scope_out, deps)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(spec_content)

    print(f"\n{'='*60}")
    print(f"✅ spec.md 已生成: {output_path.resolve()}")
    print(f"{'='*60}")

    return 0


if __name__ == "__main__":
    sys.exit(main())
