"""OpenCode adapter — generates .opencode/plugins/sylph-hooks.ts"""

from __future__ import annotations
from pathlib import Path
from typing import Any

from .base import BaseAdapter


class OpenCodeAdapter(BaseAdapter):
    name = "OpenCode"
    key = "opencode"

    def config_path(self, root: Path) -> Path:
        return root / ".opencode" / "plugins" / "sylph-hooks.ts"

    def detect(self, root: bool) -> bool:
        """Check if OpenCode is installed or configured."""
        import shutil
        if shutil.which("opencode"):
            return True
        if (Path.home() / ".config" / "opencode").is_dir():
            return True
        return False

    def generate(self, root: Path, unified: dict[str, Any],
                 hooks: dict[str, Any], event_map: dict[str, str]) -> str:
        """Generate OpenCode TypeScript plugin.

        Unlike JSON-based platforms, OpenCode uses a TypeScript plugin
        that programmatically hooks into the tool execution lifecycle.

        The plugin:
        1. Intercepts tool.execute.before for blocking hooks
        2. Intercepts tool.execute.after for auditing hooks
        3. Intercepts session.created for session initialization
        4. Intercepts chat.message for prompt processing
        """
        hooks_root = root / unified.get("meta", {}).get("hooks_root", ".claude/hooks")

        # Categorize hooks by their mapped native event (deduplicated by name+script)
        native_groups: dict[str, dict[str, str]] = {
            "tool.execute.before": {},
            "tool.execute.after": {},
            "session.created": {},
            "chat.message": {},
            "session.idle": {},
        }

        for hook_name, hook_def in hooks.items():
            script = hook_def.get("script", "")
            events = hook_def.get("events", [])
            timeout_s = hook_def.get("timeout", 5000)
            blocking = hook_def.get("blocking", False)

            for evt in events:
                native_event = event_map.get(evt)
                if native_event is None or native_event not in native_groups:
                    continue

                dedup_key = f"{hook_name}:{script}"
                if dedup_key in native_groups[native_event]:
                    continue  # skip duplicate (same hook mapped to same native event)

                rel_path = f".claude/hooks/{script}"
                entry = (
                    f'  {{ name: "{hook_name}", '
                    f'script: "{rel_path}", '
                    f'timeout: {timeout_s}, '
                    f'blocking: {"true" if blocking else "false"} }},'
                )
                native_groups[native_event][dedup_key] = entry

        def _join_entries(entries: dict[str, str], label: str) -> str:
            return "\n".join(entries.values()) if entries else f"  // No {label} configured"

        before_code = _join_entries(native_groups["tool.execute.before"], "before hooks")
        after_code = _join_entries(native_groups["tool.execute.after"], "after hooks")
        session_code = _join_entries(native_groups["session.created"], "session hooks")
        prompt_code = _join_entries(native_groups["chat.message"], "prompt hooks")
        idle_code = _join_entries(native_groups["session.idle"], "idle hooks")

        plugin = f'''// Auto-generated by .hooks/generate.py — DO NOT EDIT
// OpenCode Plugin: Sylph Harness Hooks
// Platform: OpenCode
// Generated: {unified.get("meta", {}).get("created", "unknown")}

import {{ execSync }} from "child_process";
import {{ existsSync }} from "fs";
import {{ join, resolve }} from "path";

const PROJECT_ROOT = resolve(import.meta.dirname || process.cwd(), "../..");
const DEBUG = process.env.SYLPH_HOOKS_DEBUG === "1";

interface HookEntry {{
  name: string;
  script: string;
  timeout: number;
  blocking: boolean;
}}

function runHook(entry: HookEntry, input: any): {{ continue: boolean; error?: string }} | null {{
  const absScript = join(PROJECT_ROOT, entry.script);
  if (!existsSync(absScript)) {{
    if (DEBUG) console.error(`[sylph-hooks] Script not found: ${{absScript}}`);
    return null;
  }}
  try {{
    const result = execSync(`bash "${{absScript}}"`, {{
      input: JSON.stringify(input),
      timeout: entry.timeout,
      encoding: "utf-8",
      stdio: ["pipe", "pipe", "pipe"],
    }});
    return JSON.parse(result.trim());
  }} catch (e: any) {{
    // exit code 2 = hard block (our hook protocol)
    if (e.status === 2) {{
      return {{ continue: false, error: e.stderr?.toString() || "Blocked by hook" }};
    }}
    return null;
  }}
}}

function processHooks(entries: HookEntry[], input: any): boolean {{
  for (const entry of entries) {{
    const result = runHook(entry, input);
    if (result && !result.continue) {{
      if (DEBUG) console.error(`[sylph-hooks] Blocked by ${{entry.name}}: ${{result.error}}`);
      return false;
    }}
  }}
  return true;
}}

export default async ({{ $ }}: any) => {{
  // ── Before hooks — can block execution ──
  const beforeHooks: HookEntry[] = [
{before_code}
  ];

  // ── After hooks — observe only ──
  const afterHooks: HookEntry[] = [
{after_code}
  ];

  // ── Session hooks — fire on session start ──
  const sessionHooks: HookEntry[] = [
{session_code}
  ];

  // ── Prompt hooks — fire on user message ──
  const promptHooks: HookEntry[] = [
{prompt_code}
  ];

  // ── Idle hooks — fire on session idle ──
  const idleHooks: HookEntry[] = [
{idle_code}
  ];

  return {{
    "tool.execute.before": async (input: any, _output: any) => {{
      const allowed = processHooks(beforeHooks, input);
      if (!allowed) {{
        throw new Error("Blocked by Sylph harness hook");
      }}
    }},

    "tool.execute.after": async (input: any, _output: any) => {{
      processHooks(afterHooks, input);
    }},

    "session.created": async (input: any, _output: any) => {{
      processHooks(sessionHooks, input);
    }},

    "chat.message": async (input: any, _output: any) => {{
      const allowed = processHooks(promptHooks, input);
      if (!allowed) {{
        throw new Error("Blocked by Sylph prompt hook");
      }}
    }},

    "session.idle": async (input: any, _output: any) => {{
      processHooks(idleHooks, input);
    }},
  }};
}};
'''
        return plugin

    def install(self, root: Path, config: str) -> list[Path]:
        """Write the TypeScript plugin file."""
        output_path = self.config_path(root)
        self._ensure_dir(output_path)
        with open(output_path, "w") as f:
            f.write(config)
        return [output_path]

    def summary(self, root: Path) -> dict[str, Any]:
        base = super().summary(root)
        plugins_dir = root / ".opencode" / "plugins"
        if plugins_dir.is_dir():
            ts_files = list(plugins_dir.glob("*.ts"))
            base["plugin_count"] = len(ts_files)
        return base
