#!/usr/bin/env bash
# auto-scope.sh — 从 plan.md 自动推导 current-scope.txt 范围
# 用法:
#   bash .claude/scripts/auto-scope.sh                    # 自动检测最新 plan.md
#   bash .claude/scripts/auto-scope.sh rpe/<feature>       # 指定 feature
#   bash .claude/scripts/auto-scope.sh --plan <path>       # 指定 plan.md
#
# 策略: 从 plan.md 的 "影响范围" / "文件列表" 区域提取文件路径
#       失败 fallback: 列出 prd/ 目录下最近修改的文件

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
STATE_DIR="$PROJECT_ROOT/.omc/state"
mkdir -p "$STATE_DIR"
SCOPE_FILE="$STATE_DIR/current-scope.txt"

# --- 定位 plan.md ---
PLAN_PATH=""

if [ "$1" = "--plan" ] && [ -n "$2" ]; then
    PLAN_PATH="$2"
elif [ -n "$1" ]; then
    # 尝试 rpe/{feature}/plan.md
    CANDIDATE="$PROJECT_ROOT/rpe/$1/plan.md"
    [ -f "$CANDIDATE" ] && PLAN_PATH="$CANDIDATE"
fi

# 自动检测最新 plan.md
if [ -z "$PLAN_PATH" ]; then
    CANDIDATE=$(find "$PROJECT_ROOT/rpe" -name "plan.md" -type f 2>/dev/null | xargs ls -t 2>/dev/null | head -1)
    [ -n "$CANDIDATE" ] && PLAN_PATH="$CANDIDATE"
fi

# 写入范围文件
write_scope() {
    local tmpfile; tmpfile=$(mktemp "${STATE_DIR}/auto-scope-XXXXXX.txt")
    {
        echo "# auto-generated by auto-scope.sh $(date -u +%Y-%m-%dT%H:%M:%SZ)"
        echo "# source: ${PLAN_PATH:-auto-detected}"
        echo "# entries below are file glob patterns"
        echo ""
        echo "$1" | sort -u | while IFS= read -r line; do
            [ -n "$line" ] && echo "$line"
        done
    } > "$tmpfile"
    mv "$tmpfile" "$SCOPE_FILE"
    echo "[auto-scope] wrote $(echo "$1" | grep -c . || echo 0) entries to current-scope.txt"
}

EXTRACTED=""

if [ -n "$PLAN_PATH" ]; then
    # 策略1: 从 plan.md 的 "影响范围" / "文件列表" 区块提取
    IN_SCOPE=false
    while IFS= read -r line; do
        # 检测 scope 区块标记
        if echo "$line" | grep -qiE '(影响范围|文件列表|Impact|Files? Changed|涉及文件)'; then
            IN_SCOPE=true
            continue
        fi
        # 检测下一个标题区块 → 退出 scope
        if echo "$line" | grep -qE '^## ' && $IN_SCOPE; then
            IN_SCOPE=false
        fi
        if $IN_SCOPE; then
            # 提取文件路径模式（行首 - 或 | 中间的内容）
            FILE_MATCH=$(echo "$line" | grep -oE '\`[^`]+\`' | sed 's/`//g' || true)
            [ -n "$FILE_MATCH" ] && EXTRACTED="${EXTRACTED}"$'\n'"${FILE_MATCH}"
        fi
    done < "$PLAN_PATH"

    # 策略2: 全文件 grep 引用路径
    if [ -z "$EXTRACTED" ]; then
        EXTRACTED=$(grep -oE '\.[a-zA-Z]+/[a-zA-Z0-9_/.-]+\.[a-z]+' "$PLAN_PATH" 2>/dev/null | grep -vE '(png|jpg|svg|http)' | head -30)
    fi

    if [ -n "$EXTRACTED" ]; then
        write_scope "$EXTRACTED"
        exit 0
    fi
fi

# Fallback: 无 plan.md 或无法提取范围时，不创建 scope 文件（放行模式）
# 创建无意义的 scope 文件会本末倒置——让没有范围的编辑反而被阻拦
echo "[auto-scope] no plan.md with scope found, leaving scope file absent (pass-through mode)" >&2
exit 0
