#!/usr/bin/env python3
"""auto-scope.py — 从 plan.md 自动推导 current-scope.txt 范围
Cross-platform Python resolution (DG-105)

用法:
  python3 .claude/scripts/auto-scope.py                    # 自动检测最新 plan.md
  python3 .claude/scripts/auto-scope.py rpe/<feature>       # 指定 feature
  python3 .claude/scripts/auto-scope.py --plan <path>       # 指定 plan.md

策略: 从 plan.md 的 "影响范围" / "文件列表" 区域提取文件路径
      失败 fallback: 列出 prd/ 目录下最近修改的文件
"""
import sys
import re
import json
import subprocess
import tempfile
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
PROJECT_ROOT = (SCRIPT_DIR / "../..").resolve()
STATE_DIR = PROJECT_ROOT / ".omc/state"
STATE_DIR.mkdir(parents=True, exist_ok=True)
SCOPE_FILE = STATE_DIR / "current-scope.txt"


def run(cmd, **kwargs):
    default = {"capture_output": True, "text": True, "shell": True}
    default.update(kwargs)
    result = subprocess.run(cmd, **default)
    return result.stdout.strip(), result.returncode, result.stderr


# --- 定位 plan.md ---
PLAN_PATH = ""

args = sys.argv[1:]
if len(args) >= 2 and args[0] == "--plan":
    PLAN_PATH = args[1]
elif len(args) >= 1 and args[0]:
    # 尝试 rpe/{feature}/plan.md
    candidate = PROJECT_ROOT / f"rpe/{args[0]}/plan.md"
    if candidate.is_file():
        PLAN_PATH = str(candidate)

# 自动检测最新 plan.md
if not PLAN_PATH:
    try:
        stdout, rc, stderr = run(f"find \"{PROJECT_ROOT}/rpe\" -name \"plan.md\" -type f 2>/dev/null | xargs ls -t 2>/dev/null | head -1")
        if stdout:
            PLAN_PATH = stdout
    except Exception:
        pass


def write_scope(extracted):
    """写入范围文件"""
    with tempfile.NamedTemporaryFile(
        mode="w", prefix="auto-scope-", suffix=".txt",
        dir=str(STATE_DIR), delete=False, encoding="utf-8"
    ) as tmp:
        tmp_path = Path(tmp.name)
        tmp.write(f"# auto-generated by auto-scope.py {datetime_now()}\n")
        tmp.write(f"# source: {PLAN_PATH or 'auto-detected'}\n")
        tmp.write("# entries below are file glob patterns\n\n")
        lines = sorted(set(extracted.splitlines()))
        for line in lines:
            line = line.strip()
            if line:
                tmp.write(line + "\n")

    # rename via shell (atomic)
    run(f"mv \"{tmp_path}\" \"{SCOPE_FILE}\"")
    entry_count = len([l for l in extracted.splitlines() if l.strip()])
    print(f"[auto-scope] wrote {entry_count} entries to current-scope.txt")


def datetime_now():
    from datetime import datetime, timezone
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


EXTRACTED = ""

if PLAN_PATH:
    plan_file = Path(PLAN_PATH)
    if plan_file.is_file():
        plan_text = plan_file.read_text(encoding="utf-8")
        in_scope = False
        extracted_lines = []

        for line in plan_text.splitlines():
            # 检测 scope 区块标记
            if re.search(r'(影响范围|文件列表|Impact|Files? Changed|涉及文件)', line, re.IGNORECASE):
                in_scope = True
                continue
            # 检测下一个标题区块 → 退出 scope
            if re.match(r'^## ', line) and in_scope:
                in_scope = False
            if in_scope:
                # 提取文件路径模式（反引号中的内容）
                file_matches = re.findall(r'`([^`]+)`', line)
                for fm in file_matches:
                    extracted_lines.append(fm)

        if extracted_lines:
            EXTRACTED = "\n".join(extracted_lines)

        # 策略2: 全文件 grep 引用路径
        if not EXTRACTED:
            file_refs = re.findall(r'\.[a-zA-Z]+/[a-zA-Z0-9_/.-]+\.[a-z]+', plan_text)
            file_refs = [f for f in file_refs if not re.search(r'(png|jpg|svg|http)', f)]
            EXTRACTED = "\n".join(file_refs[:30])

        if EXTRACTED:
            write_scope(EXTRACTED)
            sys.exit(0)


# Fallback: 无 plan.md 时，从 lx-goal.json 的目标描述推导范围
GOAL_DESC = ""
goal_file = STATE_DIR / "tokens/lx-goal.json"
if goal_file.is_file():
    try:
        d = json.loads(goal_file.read_text(encoding="utf-8"))
        GOAL_DESC = d.get("goal", "")
    except Exception:
        pass

if GOAL_DESC:
    # 从目标描述中提取关键词
    kws = re.findall(r'[\w.-]+\.[a-z]{1,4}|[a-z]+-[a-z]+|[A-Z][a-z]+[A-Z]', GOAL_DESC)
    dirs = re.findall(r'(scripts?|hooks?|source|docs?|packages?)', GOAL_DESC)
    goal_kw = "|".join(kws[:5] + dirs[:3])

    if goal_kw:
        matched_files = []
        for kw in re.split(r'\|', goal_kw):
            if len(kw) < 3:
                continue
            stdout, rc, stderr = run(f"git log --name-only --oneline -20 2>/dev/null | grep -i \"{kw}\" | grep -v '^[0-9a-f]\\{{7\\}}' | head -5")
            if stdout:
                matched_files.append(stdout)

        if matched_files:
            write_scope("\n".join(matched_files))
            sys.exit(0)

# 最终 Fallback: 无法推导范围，不创建 scope 文件（放行模式）
print("[auto-scope] no scope derivable from plan.md or goal, leaving scope file absent (pass-through mode)", file=sys.stderr)
sys.exit(0)
