#!/usr/bin/env python3
"""
carros_utils.py — CarrorOS 工具函数（handoff / audit / report）

从 carros_base.py 提取，保持主 CLI 文件精简。
"""

import json
from datetime import datetime, timezone
from pathlib import Path


def now_iso():
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat()


def write_handoff(token, plan_path, handoff_path):
    """写 session-handoff.md — 与 hooks 格式一致"""
    handoff_path.parent.mkdir(parents=True, exist_ok=True)
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    # 兼容新版 token 格式（无 steps 数组）
    if "plan" in token:
        # 新版兼容格式（carros_base.py 传入）
        p = token["plan"]
        done = p.get("done", 0)
        total = p.get("total", 0)
        current = p.get("current_step", "?")
        blocked = p.get("blocked")
        steps_summary = f"  current_step: {current} ({done}/{total})"
        if blocked:
            steps_summary += f"\n  blocked: {blocked}"
        sid = token.get("session", {}).get("id", "unknown")
        level = token.get("session", {}).get("level", "?")
    elif "steps" in token:
        done = token["stats"]["done"]
        total = token["stats"]["total"]
        steps_summary = "\n".join(
            f"  {'✅' if s['status'] == 'completed' else '⬜'} {s['id']}: {s['status']}"
            for s in token["steps"]
        )
        sid = token["session"]["id"]
        level = token["session"]["level"]
    else:
        done = token.get("stats", {}).get("done", 0)
        total = token.get("stats", {}).get("total", 0)
        steps_summary = f"  current_step: unknown ({done}/{total})"
        sid = token.get("session", {}).get("id", "unknown")
        level = token.get("session", {}).get("level", "?")
    plan = ""
    if plan_path and plan_path.exists():
        plan = plan_path.read_text()[:300]
    content = (
        f"# Session Handoff: {sid}\n"
        f"\n"
        f"**Updated:** {now}\n"
        f"**Level:** {level}\n"
        f"**Progress:** {done}/{total} steps\n"
        f"\n"
        f"## Steps\n"
        f"{steps_summary}\n"
        f"\n"
        f"## Plan (condensed)\n"
        f"{plan}\n"
        f"\n"
        f"---\n"
        f"_Auto-generated by carros_utils.py_\n"
    )
    handoff_path.write_text(content)


def write_audit(audit_dir, event_type, data, schema_version="v1.0"):
    """追加审计事件到当天 JSONL"""
    audit_dir.mkdir(parents=True, exist_ok=True)
    date_str = datetime.now(timezone.utc).strftime("%Y%m%d")
    audit_file = audit_dir / f"{date_str}.jsonl"
    record = {
        "schema_version": schema_version,
        "ts": datetime.now(timezone.utc).isoformat(),
        "event": event_type,
        "data": data,
    }
    with open(audit_file, "a") as f:
        f.write(json.dumps(record, ensure_ascii=False) + "\n")


def generate_final_report(token):
    """生成归档报告"""
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    sid = token.get("session", {}).get("id", "unknown")
    level = token.get("session", {}).get("level", "?")
    status = token.get("status", "?")
    stats = token.get("stats", {})

    if "steps" in token:
        done = stats["done"]
        total = stats["total"]
        tick = stats.get("tick", 0)
        step_lines = []
        for step in token["steps"]:
            icon = "✅" if step["status"] == "completed" else "⬜"
            step_lines.append(f"{icon} {step['id']}: {step['status']}")
    else:
        done = stats.get("done", 0)
        total = stats.get("total", 0)
        tick = stats.get("turns", 0)
        current = token.get("task", {}).get("current_step", "?")
        task_status = token.get("task", {}).get("status", "?")
        step_lines = [f"  current_step: {current} ({task_status})"]

    lines = [
        f"# Final Report: {sid}",
        "",
        f"**Archived at:** {now}",
        f"**Level:** {level}",
        f"**Status:** {status}",
        "",
        "## Summary",
        "",
        f"Completed {done}/{total} steps in {tick} ticks.",
        "",
        "## Steps",
        "",
    ]
    lines.extend(step_lines)
    lines.append("")
    lines.append("## Audit Trail")
    lines.append("")
    lines.append("See `.omc/state/audit/` for full event log.")
    lines.append("")
    lines.append("---")
    lines.append("_Generated by carros_utils.py archive_")
    return "\n".join(lines)
