#!/usr/bin/env python3
"""
carros_utils.py — CarrorOS 工具函数（handoff / audit / report）

从 carros_base.py 提取，保持主 CLI 文件精简。
"""

import json
import re
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional


def now_iso():
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat()


def write_handoff(token, plan_path, handoff_path):
    """写 session-handoff.md — 与 hooks 格式一致"""
    handoff_path.parent.mkdir(parents=True, exist_ok=True)
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    # 兼容新版 token 格式（无 steps 数组）
    if "plan" in token:
        # 新版兼容格式（carros_base.py 传入）
        p = token["plan"]
        done = p.get("done", 0)
        total = p.get("total", 0)
        current = p.get("current_step", "?")
        blocked = p.get("blocked")
        steps_summary = f"  current_step: {current} ({done}/{total})"
        if blocked:
            steps_summary += f"\n  blocked: {blocked}"
        sid = token.get("session", {}).get("id", "unknown")
        level = token.get("session", {}).get("level", "?")
    elif "steps" in token:
        done = token["stats"]["done"]
        total = token["stats"]["total"]
        steps_summary = "\n".join(
            f"  {'✅' if s['status'] == 'completed' else '⬜'} {s['id']}: {s['status']}"
            for s in token["steps"]
        )
        sid = token["session"]["id"]
        level = token["session"]["level"]
    else:
        done = token.get("stats", {}).get("done", 0)
        total = token.get("stats", {}).get("total", 0)
        steps_summary = f"  current_step: unknown ({done}/{total})"
        sid = token.get("session", {}).get("id", "unknown")
        level = token.get("session", {}).get("level", "?")
    plan = ""
    if plan_path and plan_path.exists():
        plan = plan_path.read_text()[:300]
    content = (
        f"# Session Handoff: {sid}\n"
        f"\n"
        f"**Updated:** {now}\n"
        f"**Level:** {level}\n"
        f"**Progress:** {done}/{total} steps\n"
        f"\n"
        f"## Steps\n"
        f"{steps_summary}\n"
        f"\n"
        f"## Plan (condensed)\n"
        f"{plan}\n"
        f"\n"
        f"---\n"
        f"_Auto-generated by carros_utils.py_\n"
    )
    handoff_path.write_text(content)


def write_audit(audit_dir, event_type, data, schema_version="v1.0"):
    """追加审计事件到当天 JSONL"""
    audit_dir.mkdir(parents=True, exist_ok=True)
    date_str = datetime.now(timezone.utc).strftime("%Y%m%d")
    audit_file = audit_dir / f"{date_str}.jsonl"
    record = {
        "schema_version": schema_version,
        "ts": datetime.now(timezone.utc).isoformat(),
        "event": event_type,
        "data": data,
    }
    with open(audit_file, "a") as f:
        f.write(json.dumps(record, ensure_ascii=False) + "\n")


# ═══════════════════════════════════════════
# 报告生成
# ═══════════════════════════════════════════

# 决策信号词 — 用于从 executor.md 中提取关键决策
DECISION_KEYWORDS = [
    # 明确决策动词
    "选择了", "决定采用", "决定使用", "改为采用",
    "方案 A", "方案 B",
    "弃用了", "放弃了", "不再使用", "跳过",
    "优先选择", "优于",
    # 决策名词
    "关键决策", "决策记录",
    "最终决定", "最终选择",
    # 决策理由
    "原因是", "理由如下",
]

# 动作信号词 — 用于从 executor.md 中提取做了什么
ACTION_SIGNALS = [
    "读了", "读取了",
    "修改了", "修复了", "创建了", "新增了", "删除了",
    "测试了", "验证了", "运行了", "执行了",
    "重构了", "重写了", "迁移了", "移植了",
    "搜索了", "调查了", "排查了", "诊断了", "分析了",
]


def _read_text(path: Path) -> str:
    """安全读文件，不存在返回空字符串"""
    if path and path.exists():
        try:
            return path.read_text(encoding="utf-8")
        except Exception:
            return ""
    return ""


def _extract_step_actions(executor_text: str, plan_text: str) -> list[dict]:
    """
    从 executor.md 提取每个 step 做了什么。
    输出: [{"id": "S1", "actions": ["读了 X 文件", "分析了 Y 架构"], "summary": "...}]
    """
    steps = []

    # 按 ## Step 或 ## S1 分块（S1 后可以有任意字符，如 "S1 · 调研方案"）
    step_pattern = re.compile(r"^##\s+(S\d+)\b", re.MULTILINE)
    if not step_pattern.search(executor_text):
        # 退一步：看 plan.md 的步骤
        plan_steps = re.findall(r"[-*]\s+\[.?\]\s+(S\d+)[:\s]*(.*)", plan_text)
        for step_id, desc in plan_steps:
            steps.append({
                "id": step_id,
                "actions": [desc.strip()] if desc.strip() else ["task initialized"],
                "summary": desc.strip() or "N/A",
            })
        return steps

    # 按 ## Sx 分块（S1 后可以有任意字符）
    splits = re.split(r"(?=^##\s+S\d+\b)", executor_text, flags=re.MULTILINE)
    for block in splits:
        m = re.match(r"^##\s+(S\d+)\b", block, re.MULTILINE)
        if not m:
            continue
        step_id = m.group(1)
        body = block[m.end():]

        # 在 body 中找证据/动作块 — 提取 "### 操作" 或 "### 输出" 下的 bullet 点
        actions = []
        # 先找操作块：### 操作 / ### 输出 下的 bullet 列表
        for ops_block in re.split(r"(?=^###\s+(?:操作|输出|产出))", body, flags=re.MULTILINE):
            ops_lines = ops_block.split("\n")
            # 跳过 ### 标题行本身
            ops_content = [l.strip() for l in ops_lines if l.strip().startswith("- ")]
            for bullet in ops_content:
                item = bullet.lstrip("- ").strip()[:120]
                if item and item not in actions:
                    actions.append(item)

        # 如果没有操作块的 bullet，回退到全文找带动作信号词的行
        if not actions:
            for line in body.split("\n"):
                line = line.strip()
                if not line or line.startswith("#") or line.startswith(">") or line.startswith("```"):
                    continue
                for signal in ACTION_SIGNALS:
                    if signal in line:
                        line_clean = line.strip("- *•").strip()[:120]
                        if line_clean and line_clean not in actions:
                            actions.append(line_clean)
                        break

        summary = ""
        summary_match = re.search(r"(?:Step|Goal)[：:]\s*(.+?)[\n\r]", block)
        if summary_match:
            summary = summary_match.group(1).strip()[:200]
        elif plan_text:
            plan_step = re.search(
                rf"[-*]\s+\[.?\]\s+{re.escape(step_id)}[:\s]*(.*)",
                plan_text,
            )
            if plan_step:
                summary = plan_step.group(1).strip()

        steps.append({
            "id": step_id,
            "actions": actions or [summary or f"执行 {step_id}"],
            "summary": summary or f"Step {step_id}",
        })

    return steps


def _extract_decisions(executor_text: str, audit_events: list[dict]) -> list[dict]:
    """
    从 executor.md + audit JSONL 提取关键决策。
    输出: [{"decision": "...", "reason": "...", "source": "executor.md / audit"}]
    """
    decisions = []

    # 从 executor.md 提取 — 找 ### 决策 块下的内容
    # 按 ### 决策 分块
    decision_blocks = re.split(r"(?=^###\s+决策)", executor_text, flags=re.MULTILINE)
    for d_block in decision_blocks:
        if not d_block.strip():
            continue
        # 检查是否是 ### 决策 块的开头
        if not re.search(r"^###\s+决策", d_block, re.MULTILINE):
            continue

        # 提取该块下的所有内容（直到下一个 ### 或 ##）
        lines = d_block.split("\n")
        body_start = False
        current_lines = []
        for line in lines:
            if body_start:
                # 遇到下一个 ### 或 ## 就结束
                if re.match(r"^#{2,3}\s+", line):
                    break
                current_lines.append(line)
            elif re.search(r"^###\s+决策", line):
                body_start = True

        body_text = "\n".join(current_lines).strip()
        if not body_text:
            continue

        # 从 bullet 点提取
        bullet_decisions = re.findall(r"^- (.+)$", body_text, re.MULTILINE)
        for bullet in bullet_decisions:
            decisions.append({
                "decision": bullet.strip()[:200],
                "reason": "",
                "source": "executor.md",
            })

        # 没有 bullet 时，用全文
        if not bullet_decisions:
            # 找第一句或者关键句
            for line in current_lines:
                line = line.strip()
                if not line:
                    continue
                decisions.append({
                    "decision": line[:200],
                    "reason": "",
                    "source": "executor.md",
                })

    # 从 audit 事件中提取决策事件
    for event in audit_events:
        event_type = event.get("event", "") or event.get("event_type", "")
        data = event.get("data", {})
        if not data and "ts" in event:
            data = event  # 可能是扁平格式

        decision_text = ""
        reason_text = ""

        if event_type in ("oracle_decision",):
            decision_text = f"Oracle: {data.get('decision', '?')}"
            reason_text = data.get("reason", "")
        elif event_type in ("fallback_event", "fallback"):
            decision_text = f"Fallback: {data.get('decision', '?')}"
            reason_text = data.get('reason', '') or data.get('failure_type', '')
        elif event_type == "archive_completed":
            decision_text = "归档完成"
            reason_text = "所有步骤已验证并归档"
        elif event_type in ("blocked",):
            decision_text = "任务阻塞"
            reason_text = data.get("reason", "")
        elif event_type in ("verify_decision",):
            decision_text = f"验证: {data.get('step', '?')} → {data.get('decision', '?')}"
            reason_text = ""

        if decision_text:
            decisions.append({
                "decision": decision_text[:200],
                "reason": reason_text[:200] if reason_text else "N/A",
                "source": "audit",
            })

    # 去重
    seen = set()
    unique = []
    for d in decisions:
        key = d["decision"][:60]
        if key not in seen:
            seen.add(key)
            unique.append(d)
    return unique


def _extract_stats_from_token(token: dict) -> dict:
    """从 token 提取执行统计"""
    stats = token.get("stats", {})
    sid = token.get("session", {}).get("id", "unknown")
    level = token.get("session", {}).get("level", "?")
    status = token.get("status", "?")
    done = stats.get("done", 0)
    total = stats.get("total", 0)
    ticks = stats.get("turns", 0) or stats.get("tick", 0)
    return {
        "task_id": sid,
        "level": level,
        "status": status,
        "done": done,
        "total": total,
        "ticks": ticks,
    }


def _extract_goal_from_token(token: dict) -> str:
    """从 token 提取 goal"""
    goal = token.get("task", {}).get("goal", "")
    if not goal:
        goal = token.get("goal", "")
    if isinstance(goal, dict):
        goal = goal.get("goal", "") or goal.get("intent", "") or goal.get("description", "")
    return str(goal).strip() if goal else "N/A"


def generate_final_report(token: dict, task_dir: Optional[Path] = None) -> str:
    """
    生成最终报告 — 从 executor.md + plan.md + audit JSONL 提取。
    不会编造，数据源中没有的内容会标注「无记录」。

    Args:
        token: 当前任务 token（dict 格式）
        task_dir: 任务目录路径（可选，用于读 executor.md/plan.md/audit）
    """
    now_str = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    stats = _extract_stats_from_token(token)
    goal = _extract_goal_from_token(token)

    executor_text = ""
    plan_text = ""
    audit_events: list[dict] = []

    if task_dir:
        executor_text = _read_text(task_dir / "executor.md")
        plan_text = _read_text(task_dir / "plan.md")

        # 读审计日志
        audit_dir = Path(".omc/audit")
        if audit_dir.exists():
            for f in sorted(audit_dir.glob("*.jsonl")):
                try:
                    for line in f.read_text().split("\n"):
                        line = line.strip()
                        if line:
                            audit_events.append(json.loads(line))
                except (json.JSONDecodeError, OSError):
                    pass

        # 也读 sub_task 目录下的 executor.md
        sub_task_dir = task_dir / "sub_task"
        if sub_task_dir.exists():
            for sub_dir in sorted(sub_task_dir.iterdir()):
                if sub_dir.is_dir():
                    sub_exec = _read_text(sub_dir / "executor.md")
                    if sub_exec:
                        executor_text += "\n\n" + sub_exec
                    sub_inst = _read_text(sub_dir / "instruction.md")
                    if sub_inst and not executor_text:
                        executor_text += "\n---\n" + sub_inst

    # 提取做了什么
    step_actions = _extract_step_actions(executor_text, plan_text)

    # 提取关键决策
    decisions = _extract_decisions(executor_text, audit_events)

    # 交叉验证：stats vs actual
    verification_notes = []
    if step_actions:
        found_ids = {s["id"] for s in step_actions if s["actions"]}
        expected = set()
        for i in range(1, int(stats["total"]) + 1):
            expected.add(f"S{i}")
        missing = expected - found_ids
        if missing:
            verification_notes.append(f"⚠ token 记录 {stats['done']}/{stats['total']} 步，但 executor.md 中缺少步骤: {', '.join(sorted(missing))}")

    lines = [
        f"# Final Report: {stats['task_id']}",
        "",
        f"**归档时间:** {now_str}",
        f"**Level:** {stats['level']}",
        f"**状态:** {stats['status']}",
        f"**完成度:** {stats['done']}/{stats['total']} 步",
        f"**执行轮次:** {stats['ticks']}",
        "",
        "---",
        "",
        "## 任务目标",
        "",
        goal,
        "",
        "---",
        "",
        "## 做了什么",
        "",
    ]

    if not step_actions:
        lines.append("_无记录_")
        lines.append("")
    else:
        for step in step_actions:
            lines.append(f"### {step['id']}")
            lines.append("")
            if step["summary"] and step["summary"] != f"Step {step['id']}":
                lines.append(f"{step['summary']}")
                lines.append("")
            if step["actions"]:
                for a in step["actions"]:
                    lines.append(f"- {a}")
                lines.append("")
            else:
                lines.append("_无详细操作记录_")
                lines.append("")

    lines.append("---")
    lines.append("")

    lines.append("## 关键决策")
    lines.append("")

    if not decisions:
        lines.append("_无记录_")
        lines.append("")
        lines.append("> 决策记录是理解任务推进逻辑的关键。请在执行过程中记录关键决策（如方案选择、架构变更、技术权衡）。")
        lines.append("")
    else:
        for i, d in enumerate(decisions, 1):
            lines.append(f"### 决策 {i}")
            lines.append("")
            lines.append(f"**决策:** {d['decision']}")
            lines.append("")
            if d['reason'] and d['reason'] != 'N/A':
                lines.append(f"**理由:** {d['reason']}")
                lines.append("")
            lines.append(f"*来源: {d['source']}*")
            lines.append("")

    lines.append("---")
    lines.append("")

    if verification_notes:
        lines.append("## 验证说明")
        lines.append("")
        lines.extend(verification_notes)
        lines.append("")

    lines.append("## 审计轨迹")
    lines.append("")
    lines.append("完整事件日志见 `.omc/audit/` 目录。")
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append(f"_生成于 {now_str}_")
    lines.append("_本报告从 executor.md + audit 日志 + token 提取事实，不会编造。_")

    return "\n".join(lines)
