#!/usr/bin/env python3
"""Meta-Oracle trigger hook — PostToolUse event, G1-G4 gate detection.

Replaces meta-oracle-trigger.sh with pure Python3, cross-platform
(macOS / Linux / Windows) and zero external dependencies.

4 trigger points (priority G1 > G2 > G4 > G3):
  G1 - Architecture decision final review (>=2 subsystems + irreversible)
  G2 - PRD/plan final step (Oracle ACCEPT + lifecycle completion signal)
  G3 - Oracle ACCEPT + high score (>=8.5)
  G4 - Release gate (package-release.sh execution)

Soft gate: issues verdict + recommendation; AI may override with explicit rationale.
"""

import json
import os
import re
import sys
import time
from datetime import datetime


# ── Platform detection ──────────────────────────────────────────────
IS_WINDOWS = os.name == "nt"
HOME = os.path.expanduser("~")


def _resolve_project_root():
    """Derive project root from this script's location, cross-platform."""
    script_dir = os.path.dirname(os.path.abspath(__file__))
    return os.path.abspath(os.path.join(script_dir, "..", ".."))


PROJECT_ROOT = _resolve_project_root()
STATE_DIR = os.path.join(PROJECT_ROOT, ".omc", "state")


# ── Feature gate (replaces hc_enabled from harness_config.sh) ──────

def _is_feature_enabled():
    """Check harness.yaml / .harness-cache for meta_oracle_trigger.

    Returns True if enabled, False if explicitly disabled.
    Default: True (fail-open for safety gate).
    """
    # Priority 1: harness.yaml
    yaml_path = os.path.join(PROJECT_ROOT, ".claude", "harness.yaml")
    if os.path.isfile(yaml_path):
        try:
            with open(yaml_path, "r", encoding="utf-8") as f:
                for line in f:
                    stripped = line.strip()
                    if "meta_oracle_trigger" in stripped:
                        # Match patterns like:
                        #   meta_oracle_trigger: true
                        #   meta_oracle_trigger: false
                        if re.search(r":\s*false", stripped, re.IGNORECASE):
                            return False
                        if re.search(r":\s*true", stripped, re.IGNORECASE):
                            return True
        except OSError:
            pass

    # Priority 2: .harness-cache (generated by generate.py for non-CC platforms)
    cache_path = os.path.join(PROJECT_ROOT, ".hooks", ".cache")
    if os.path.isfile(cache_path):
        try:
            with open(cache_path, "r", encoding="utf-8") as f:
                for line in f:
                    if "hooks_enabled.meta_oracle_trigger=false" in line:
                        return False
                    if "hooks_enabled.meta_oracle_trigger=true" in line:
                        return True
        except OSError:
            pass

    # Priority 3: default enabled
    return True


# ── JSON I/O ────────────────────────────────────────────────────────

def _read_stdin_json():
    """Read and parse stdin as JSON from the hook harness."""
    raw = sys.stdin.read()
    if not raw.strip():
        return {}
    try:
        return json.loads(raw)
    except json.JSONDecodeError:
        return {}


def _extract_combined_text(input_data):
    """Extract combined text from tool_name + tool_response for G1-G4 detection.

    Handles multiple platform field names (Claude Code, OpenCode, Codex).
    """
    tool_name = input_data.get("tool_name", "") or ""

    tr = input_data.get("tool_response", {})
    if isinstance(tr, str):
        tr = {"content": tr}

    parts = []
    for key in ("stdout", "content", "message", "text"):
        val = tr.get(key, "")
        if isinstance(val, str) and val.strip():
            parts.append(val)
        elif isinstance(val, (list, dict)):
            parts.append(json.dumps(val))

    combined = f"{tool_name} {' '.join(parts)}"
    return combined


def _emit_json(continue_val=True, additional_context=None):
    """Output hook response JSON (replaces hc_emit_hook_json)."""
    result: dict = {"continue": continue_val}
    if additional_context:
        result["hookSpecificOutput"] = {
            "hookEventName": "PostToolUse",
            "additionalContext": additional_context.strip(),
        }
    # ensure_ascii=True prevents lone surrogate crashes (DG-88/DG-009)
    print(json.dumps(result, ensure_ascii=True))


# ── Cooldown + escalation ───────────────────────────────────────────

def _read_state_file(filename, default=""):
    """Read a state file, return stripped content or default."""
    path = os.path.join(STATE_DIR, filename)
    try:
        with open(path, "r", encoding="utf-8") as f:
            return f.read().strip()
    except (OSError, FileNotFoundError):
        return default


def _write_state_file(filename, content):
    """Write a state file, creating state dir if needed."""
    os.makedirs(STATE_DIR, exist_ok=True)
    path = os.path.join(STATE_DIR, filename)
    with open(path, "w", encoding="utf-8") as f:
        f.write(str(content))


def _check_cooldown():
    """Return True if Meta-Oracle should be suppressed by cooldown (1hr)."""
    last_trigger = _read_state_file(".meta-oracle-cooldown")
    if not last_trigger:
        return False
    try:
        last_ts = int(last_trigger)
    except ValueError:
        return False
    now = int(time.time())
    return (now - last_ts) < 3600  # 1 hour cooldown


def _check_escalation_disabled():
    """Return True if escalation counter > 5 with no verdict (self-disable, M4 fix)."""
    count_str = _read_state_file(".meta-oracle-trigger-count", "0")
    try:
        count = int(count_str)
    except ValueError:
        count = 0
    if count <= 5:
        return False
    verdicts_path = os.path.join(STATE_DIR, "meta-oracle-verdicts.md")
    if not os.path.isfile(verdicts_path):
        return True
    try:
        line_count = sum(1 for _ in open(verdicts_path, "r", encoding="utf-8"))
    except OSError:
        line_count = 0
    return line_count < 2


def _record_trigger():
    """Write cooldown timestamp and increment trigger counter."""
    _write_state_file(".meta-oracle-cooldown", str(int(time.time())))
    count_str = _read_state_file(".meta-oracle-trigger-count", "0")
    try:
        count = int(count_str)
    except ValueError:
        count = 0
    _write_state_file(".meta-oracle-trigger-count", str(count + 1))


# ── Flywheel event logging ──────────────────────────────────────────

def _flywheel_event(hook, event, severity="P2"):
    """Append structured event to flywheel.log (replaces flywheel_event bash fn)."""
    log_path = os.path.join(HOME, ".claude", "flywheel.log")
    today = datetime.now().strftime("%Y-%m-%d")
    project = os.path.basename(PROJECT_ROOT)
    line = f"{today},{hook}_{event},{severity},{project}\n"
    try:
        os.makedirs(os.path.dirname(log_path), exist_ok=True)
        with open(log_path, "a", encoding="utf-8") as f:
            f.write(line)
    except OSError:
        pass  # Non-blocking


# ── G1-G4 trigger detection ─────────────────────────────────────────

def _filter_system_reminders(text):
    """Remove <system-reminder> tags to prevent self-loop triggers."""
    return re.sub(r"<system-reminder>[^<]*</system-reminder>", "", text, flags=re.DOTALL)


def _detect_g1(combined):
    """G1: Architecture decision final review.

    >=2 subsystems + irreversible change + Oracle ACCEPT.
    """
    # Step 1: architecture decision context
    arch_ctx = re.search(
        r"(?:架构|architecture|子系统|subsystem|domain.*split|功能域)"
        r".*(?:决策|decision|终审|final|不可逆|irreversible)",
        combined,
        re.IGNORECASE,
    )
    if not arch_ctx:
        return False

    # Step 2: must have Oracle ACCEPT
    if not re.search(r"(?:Oracle|oracle).*(?:ACCEPT|APPROVED|通过)", combined):
        return False

    # Step 3: irreversible marker OR multi-subsystem signal (>=3)
    if re.search(
        r"不可逆|irreversible|[3-9]\s*(?:个|子系|功能域|domain|subsystem)",
        combined,
        re.IGNORECASE,
    ):
        return True

    return False


def _detect_g2(combined):
    """G2: PRD/plan final step — Oracle ACCEPT + lifecycle completion signal."""
    if not re.search(r"(?:Oracle|oracle).*(?:ACCEPT|APPROVED)", combined):
        return False
    if re.search(
        r"(?:PRD.*终审|方案.*完成|report.*complete|phase.*accept|"
        r"phase.*complete|plan.*accept)",
        combined,
        re.IGNORECASE,
    ):
        return True
    return False


def _detect_g4(combined):
    """G4: Release gate — package-release.sh invocation detected."""
    if re.search(r"package-release\.sh|release.*(?:打包|package|发布)", combined, re.IGNORECASE):
        return True
    return False


def _detect_g3(combined):
    """G3: Oracle ACCEPT/APPROVED or high score (>=8.5)."""
    # Oracle ACCEPT/APPROVED signal
    if re.search(r"(?:Oracle|oracle).*(?:ACCEPT|APPROVED|approve|accept)", combined):
        return True

    # High score detection
    scores = re.findall(
        r"(?:score|Score|评分|得分)[：: ]*(\d+\.\d+)", combined
    )
    if scores:
        max_score = max(float(s) for s in scores)
        if max_score >= 8.5:
            return True

    # Overall / weighted score
    overall = re.findall(
        r"(?:综合|总分|平均|overall)[：: ]*(\d+\.\d+)", combined
    )
    if overall:
        max_os = max(float(s) for s in overall)
        if max_os >= 8.5:
            return True

    return False


def _detect_trigger(combined):
    """Run G1-G4 detection in priority order. Returns (priority, reason) or (None, None)."""
    # G1: Architecture decision
    if _detect_g1(combined):
        return ("G1", "G1 架构决策终审 — ≥2 子系统 + 不可逆变更 + Oracle 已 ACCEPT")

    # G2: PRD final step
    if _detect_g2(combined):
        return ("G2", "G2 PRD/方案最后一步 — PRD 生命周期完成 + Oracle 已 ACCEPT")

    # G4: Release gate
    if _detect_g4(combined):
        return ("G4", "G4 Release 门禁 — package-release.sh 执行前安全检查")

    # G3: Oracle ACCEPT / high score
    if _detect_g3(combined):
        # Determine specific reason
        if re.search(r"(?:Oracle|oracle).*(?:ACCEPT|APPROVED)", combined):
            return ("G3", "G3 Oracle ACCEPT/APPROVED 裁决检测")
        scores = re.findall(r"(?:score|Score|评分|得分)[：: ]*(\d+\.\d+)", combined)
        if scores:
            max_score = max(float(s) for s in scores)
            if max_score >= 8.5:
                return ("G3", f"G3 Oracle 高分评分 ({max_score} ≥ 8.5)")
        overall = re.findall(r"(?:综合|总分|平均|overall)[：: ]*(\d+\.\d+)", combined)
        if overall:
            max_os = max(float(s) for s in overall)
            if max_os >= 8.5:
                return ("G3", f"G3 综合评分 ≥ 8.5 ({max_os})")

    return (None, None)


# ── Trigger message template ─────────────────────────────────────────

def _build_trigger_message(priority, reason):
    """Build the Meta-Oracle trigger notification (mirrors bash version output)."""
    py_cmd = "py -3" if IS_WINDOWS else "python3"
    return (
        f"🔍 [Meta-Oracle {priority} 触发] {reason}\n"
        f"→ Meta-Oracle = 最后守门员（核武器级终审），权威高于 Oracle\n"
        f"→ 软门禁: 给出 ACCEPT/ADVISORY/REJECT 裁决，AI 可在明确理由下覆写\n"
        f"→ 执行方式: Agent(critic, 独立上下文, 模型无关) — 运行时验证 > 静态检查\n"
        f"→ 审查脚本: {py_cmd} .claude/scripts/meta-oracle-review.py {priority}\n"
        f"→ 裁决留痕: .omc/state/meta-oracle-verdicts.md\n"
        f"→ 注意: 同一任务最多触发 1 次 Meta-Oracle，请珍惜使用"
    )


# ── Main ─────────────────────────────────────────────────────────────

def main():
    # Feature gate
    if not _is_feature_enabled():
        _emit_json(continue_val=True)
        return

    # Read and parse stdin
    input_data = _read_stdin_json()
    if not input_data:
        _emit_json(continue_val=True)
        return

    combined = _extract_combined_text(input_data)
    if not combined.strip():
        _emit_json(continue_val=True)
        return

    # Input size guard (C2 fix: prevent grep timeout on large payloads)
    combined = combined[:10000]

    # Cooldown check
    if _check_cooldown():
        _emit_json(continue_val=True)
        return

    # Escalation self-disable (M4 fix)
    if _check_escalation_disabled():
        msg = "[meta-oracle] SELF-DISABLED: triggered >5 times with no verdict recorded"
        print(msg, file=sys.stderr)
        _emit_json(continue_val=True)
        return

    # Filter system-reminder tags (prevent self-loop)
    combined = _filter_system_reminders(combined)

    # Detect trigger
    priority, reason = _detect_trigger(combined)

    if priority is None:
        _emit_json(continue_val=True)
        return

    # Record trigger
    _record_trigger()

    # Log flywheel event
    _flywheel_event("meta_oracle_trigger", "triggered", "P2")

    # Emit trigger notification
    message = _build_trigger_message(priority, reason)
    _emit_json(continue_val=True, additional_context=message)

    # Also log to stderr for debugging
    print(
        f"[meta-oracle] {priority}: {reason} — Meta-Oracle 最后守门提醒已注入",
        file=sys.stderr,
    )


if __name__ == "__main__":
    main()
